# -*- coding: utf-8 -*-
"""Лабораторная 12122024 Никитин А.Ю.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bd87VbRzCVPaktYh8I6lqtXl9eGmqVp0
"""

import os
import threading
from flask import Flask
import sqlite3
from flask import render_template

import socket

app = Flask(__name__, template_folder='/content')


@app.route('/')
def index():
  connection = sqlite3.connect('my_datebase.db')
  cursor = connection.cursor()

  cursor.execute('''
  CREATE TABLE IF NOT EXISTS Gifts (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  gift TEXT NOT NULL,
  cost INTEGER,
  status TEXT NOT NULL
  )
  ''')

  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Egor', 'Pencil', 23, 'Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Anna', 'Ball', 100, 'НЕ Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Ivan', 'Computer', 5000, 'Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Sergey', 'Scotch', 5, 'НЕ Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Svetlana', 'Water', 20, 'Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Fedor', 'Monitor', 500, 'Не Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Irina', 'Car', 100056, 'Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Frol', 'Glass', 50, 'НЕ Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Vadim', 'Phone', 1500, 'Купили'))
  cursor.execute('INSERT INTO Gifts (name, gift, cost, status) VALUES (?, ?, ?, ?)', ('Nina', 'Back', 567, 'Не Купили'))

  connection.commit()

  cursor.execute('SELECT * FROM Gifts')
  gifts = cursor.fetchall()

  connection.close()

  return render_template('index.html', gifts = gifts)

threading.Thread(target=app.run, kwargs={'host':'0.0.0.0', 'port':80}).start()

import requests

r = requests.get('http://172.28.0.12/')
print(r.status_code)
print(r.encoding)
print(r.apparent_encoding)
print(r.text)